apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  init-harbor.sh: |
    #!/bin/sh
    set -e
    echo "Setting up initial harbor state"
    HARBOR_URL="harbor-harbor-core:80/api/projects/1"

    # Set up initial state for harbor.
    EXISTS=$(curl -k -X GET -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.code') 
  
    if [ "$EXISTS" != "404" ]
    then
        NAME=$(curl -k -X GET -u admin:Harbor12345 {{ .Values.endpoint }}/projects/1 | jq '.name')

        if [ "$NAME" == "\"library\"" ]
        then
            # Deletes the default project "library"
            echo Removing project library from harbor
            # Curl will retrun status 500 even though it successfully removed the project.
            curl -k -X DELETE -u admin:{{ .Values.password }} {{ .Values.endpoint }}/projects/1 > /dev/null

            # Creates new private project "default"
            echo "Creating new private project default"
            curl -k -X POST -u admin:{{ .Values.password }} {{ .Values.endpoint }}/projects --header 'Content-Type: application/json' --header 'Accept: application/json' --data '{
                "project_name": "default",
                "metadata": {
                    "public": "0",
                    "enable_content_trust": "false",
                    "prevent_vul": "false",
                    "severity": "low",
                    "auto_scan": "true"
                }
            }'
            echo "Harbor initialized"
        fi
    else
        echo "Harbor was already initilized"
    fi
