apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: run
          image: elastisys/curl-jq:latest
          command: ['/bin/sh', '/scripts/init-harbor.sh']
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: {{ .Release.Name }}-cm
