apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: influxdb-metric-retention
  labels:
    app: influxdb-metric-retention
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: influxdb-metric-retention
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: config-volume
              configMap:
                # Provide the name of the ConfigMap containing the files you want
                # to add to the container
                name: special-config
          containers:
          - name: influxdb-metric-retention
            image: python:3.8-alpine
            volumeMounts:
            - name: backups
              mountPath: /backups
            command:
            - python3
            args:
            - influxdb-size-based-metrics-retention.py
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 250m
                memory: 500Mi