repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

helmDefaults:
  tillerNamespace: kube-system 
  tls: true
  timeout: 300
  wait: false

  # {{ if eq .Environment.Name "vault_cluster" }}
  # tlsCACert: "../certs/vault_cluster/kube-system/certs/ca.pem"
  # tlsCert: "../certs/vault_cluster/kube-system/certs/helm.pem"
  # tlsKey: "../certs/vault_cluster/kube-system/certs/helm-key.pem"
  # {{ end }}

environments:
  vault_cluster:

releases:
- name: nfs-client-provisioner
  namespace: kube-system
  labels:
    app: nfs-client-provisioner
  chart: stable/nfs-client-provisioner
  version: 1.2.6
  missingFileHandler: error
  wait: true
  values:
  {{ if eq .Environment.Name "vault_cluster" }}
  - values/nfs-client-provisioner-vault.yaml.gotmpl
  {{ end }}

- name: vault
  namespace: vault
  labels:
    app: vault
  chart: "../charts/vault-helm/"
  version: 0.1.2
  missingFileHandler: error
  # We cannot wait since we need to manually initialize vault.
  wait: false
  values:
  - "../charts/vault-helm/values.yaml"
  - "../vault-config/values.yaml"

- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  chart: jetstack/cert-manager
  version: v0.10.0
  missingFileHandler: error
  wait: true
