apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-wc-reader
  name: prometheus-wc-reader
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus-wc-reader
  type: ClusterIP
