apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-wc-reader
  name: prometheus-wc-reader
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    key: prometheus-federate-additional.yaml
    name: prometheus-wc-scrape-configs

  enableAdminAPI: false
  logFormat: logfmt
  logLevel: info
  remoteRead:
  - read_recent: true
    url: http://influxdb.influxdb-prometheus.svc.cluster.local:8086/api/v1/prom/read?db=workload_cluster&u=demo&p=demo-pass
  remoteWrite:
  - url: http://influxdb.influxdb-prometheus.svc.cluster.local:8086/api/v1/prom/write?db=workload_cluster&u=demo&p=demo-pass
  replicas: 1
  retention: 10d
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-operator-prometheus
  serviceMonitorSelector:
    matchLabels:
      target: none  # so that operator wont generate new config
