# Chart repositories used from within this state file.
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: kiwigrid
  url: https://kiwigrid.github.io
- name: vmware-tanzu
  url: https://vmware-tanzu.github.io/helm-charts

# service_cluster specific repositories
{{ if eq .Environment.Name "service_cluster" }}
- name: harbor
  url: https://helm.goharbor.io
{{ end }}

# Defults settings to use with helm and tiller.
helmDefaults:
  tillerNamespace: kube-system  #dedicated default key for tiller-namespace
  tls: true
  timeout: 600
  wait: false

  # TODO: Use env or Env.values instead of fixed paths for certs.
  {{ if eq .Environment.Name "service_cluster" }}
  tlsCACert: "{{ requiredEnv "CONFIG_PATH" }}/certs/service_cluster/kube-system/certs/ca.pem"
  tlsCert: "{{ requiredEnv "CONFIG_PATH" }}/certs/service_cluster/kube-system/certs/helm.pem"
  tlsKey: "{{ requiredEnv "CONFIG_PATH" }}/certs/service_cluster/kube-system/certs/helm-key.pem"
  {{ end }}
  {{ if eq .Environment.Name "workload_cluster" }}
  tlsCACert: "{{ requiredEnv "CONFIG_PATH" }}/certs/workload_cluster/kube-system/certs/ca.pem"
  tlsCert: "{{ requiredEnv "CONFIG_PATH" }}/certs/workload_cluster/kube-system/certs/helm.pem"
  tlsKey: "{{ requiredEnv "CONFIG_PATH" }}/certs/workload_cluster/kube-system/certs/helm-key.pem"
  {{ end }}


# Environments
environments:
  workload_cluster:
  service_cluster:

# The desired state of Helm releases.
releases:
# Nginx-ingress
- name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.26.2
  missingFileHandler: error
  wait: true
  values:
  - values/nginx-ingress.yaml.gotmpl

# NFS
- name: nfs-client-provisioner
  namespace: kube-system
  labels:
    app: nfs-client-provisioner
  chart: stable/nfs-client-provisioner
  version: 1.2.6
  missingFileHandler: error
  wait: true
  values:
  {{ if eq .Environment.Name "service_cluster" }}
  - values/nfs-client-provisioner-sc.yaml.gotmpl
  {{ end }}
  {{ if eq .Environment.Name "workload_cluster" }}
  - values/nfs-client-provisioner-wc.yaml.gotmpl
  {{ end }}

# Cert-manager
- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  chart: jetstack/cert-manager
  version: v0.10.0
  missingFileHandler: error
  wait: true

# Prometheus-operator
- name: prometheus-operator
  namespace: monitoring
  labels:
    app: prometheus-operator
  chart: stable/prometheus-operator
  version: 8.3.3
  missingFileHandler: error
  values:
{{ if eq .Environment.Name "service_cluster" }}
  - values/prometheus-operator-sc.yaml.gotmpl
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/prometheus-operator-wc.yaml.gotmpl
{{ end }}

- name: ck8sdash
  namespace: ck8sdash
  labels:
    app: ck8sdash
  chart: ./charts/ck8sdash
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/ck8sdash-common.yaml.gotmpl
{{ if eq .Environment.Name "service_cluster" }}
  - values/ck8sdash-sc.yaml.gotmpl
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/ck8sdash-wc.yaml.gotmpl
{{ end }}

# Service cluster releases
{{ if eq .Environment.Name "service_cluster" }}
# Dex
- name: dex
  namespace: dex
  labels:
    app: dex
  chart: stable/dex
  version: 2.5.0
  missingFileHandler: error
  wait: true
  values:
  - values/dex.yaml.gotmpl

{{ if eq (env "ENABLE_CUSTOMER_PROMETHEUS") "true" }}
# Prometheus-instance for scraping customer metrics
- name: customer-scraper
  namespace: monitoring
  labels:
    app: customer-federate-scraper
  chart: ./charts/prometheus-instance
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/prometheus-customer-federate-scraper.yaml.gotmpl
{{ end }}
# Prometheus-instance for scraping workload cluster metrics
- name: wc-scraper
  namespace: monitoring
  labels:
    app: customer-federate-scraper
  chart: ./charts/prometheus-instance
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/prometheus-wc-federate-scraper.yaml.gotmpl

{{ if eq (env "ENABLE_CUSTOMER_GRAFANA") "true" }}
# Grafana instance for customer
- name: customer-grafana
  namespace: monitoring
  labels:
    app: customer-grafana
  chart: stable/grafana
  version: 4.2.2
  missingFileHandler: error
  values:
  - values/grafana-customer.yaml.gotmpl
{{ end }}

#Elasticsearch-prometheus-exporter
- name: elasticsearch-prometheus-exporter
  namespace: elastic-system
  labels:
    app: elasticsearch-prometheus-exporter
  chart: stable/elasticsearch-exporter
  version: 2.1.1
  missingFileHandler: error
  values:
  - values/elasticsearch-prometheus-exporter.yaml.gotmpl

# configure elasticsearch
- name: configure-es
  namespace: elastic-system
  labels:
    app: config
  chart: ./charts/configure-es
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/configure-es.yaml.gotmpl

# Harbor
- name: harbor-certs
  namespace: harbor
  labels:
    app: harbor
  chart: ./charts/harbor-certs
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/harbor-certs.yaml.gotmpl

- name: harbor
  namespace: harbor
  labels:
    app: harbor
  chart: harbor/harbor
  version: 1.3.0
  missingFileHandler: error
  wait: true
  timeout: 600
  values:
  - values/harbor.yaml.gotmpl

- name: init-harbor
  namespace: harbor
  labels:
    app: harbor
  chart: ./charts/init-harbor
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/init-harbor.yaml.gotmpl

# InfluxDB with disk usage monitoring and metrics retention
# Generated with helmify script using kustomize
- name: influxdb
  namespace: influxdb-prometheus
  labels:
    app: influxdb
  chart: ./charts/influxdb # Specifies the target directory of Helm Chart generated using kustomize based on the stable/influxdb (as specified in kustomize/ifluxdb/base/influxdb/chartInflator.yaml file)
  version: 0.1.0
  hooks:
  - events: ["prepare", "cleanup"]
  # - events: ["prepare"]  
    command: "./helmify.sh"
    args: ["{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}", "{{`{{.Release.Chart}}`}}", "{{`{{.Environment.Name}}`}}"]

- name: blackbox
  namespace: monitoring
  labels:
    app: blackbox
  chart: ./charts/blackbox
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/blackbox.yaml.gotmpl

# Fluentd
- name: fluentd
  namespace: fluentd
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: error
  values:
  - values/fluentd-sc.yaml.gotmpl

# Fluentd aggregator
- name: fluentd-aggregator
  namespace: fluentd
  labels:
    app: fluentd-aggregator
  chart: stable/fluentd
  version: 2.3.2
  missingFileHandler: error
  values:
  - values/fluentd-aggregator.yaml.gotmpl

# Velero
- name: velero
  namespace: velero
  labels:
    app: velero
  chart: vmware-tanzu/velero
  version: 2.8.2
  missingFileHandler: error
  values:
  - values/velero-sc.yaml.gotmpl

# End of system services releases
{{ end }}

# Workload cluster releases
{{ if eq .Environment.Name "workload_cluster"  }}
# Falco
- name: falco
  namespace: falco
  labels:
    app: falco
  chart: stable/falco
  version: 1.0.11
  missingFileHandler: error
  values:
  - values/falco.yaml.gotmpl

# Fluentd
- name: fluentd-system
  namespace: kube-system
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: error
  values:
  - values/fluentd-wc.yaml.gotmpl

# Fluentd configurable by the customer
- name: fluentd
  namespace: fluentd
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: error
  values:
  - values/fluentd-customer.yaml.gotmpl

# opa
- name: opa
  namespace: opa
  labels:
    app: opa
  chart: stable/opa
  version: 1.6.0
  missingFileHandler: error
  values:
  - values/opa.yaml.gotmpl

# opa policies
{{ if eq (env "ENABLE_OPA") "true" }}
- name: opa-policies
  namespace: opa
  labels:
    app: opa
  chart: ./charts/opa-policies
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/opa-policies.yaml.gotmpl
{{ end }}

# Velero
- name: velero
  namespace: velero
  labels:
    app: velero
  chart: vmware-tanzu/velero
  version: 2.8.2
  missingFileHandler: error
  values:
  - values/velero-wc.yaml.gotmpl

# Customer RBAC
- name: customer-rbac
  namespace: kube-system
  labels:
    app: customer-rbac
  chart: ./charts/customer-rbac
  version: 0.1.0
  missingFileHandler: error
  values:
  - values/customer-rbac.yaml.gotmpl
{{ end }}
