# Chart repositories used from within this state file.
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: kiwigrid
  url: https://kiwigrid.github.io
- name: vmware-tanzu
  url: https://vmware-tanzu.github.io/helm-charts

# service_cluster specific repositories
{{ if eq .Environment.Name "service_cluster" }}
- name: harbor
  url: https://helm.goharbor.io
- name: elastisys
  url: https://elastisys.github.io/chart-repo
{{ end }}

# Defult settings to use with helm.
helmDefaults:
  timeout: 600
  createNamespace: false

# Environments
environments:
  workload_cluster:
  service_cluster:

# The desired state of Helm releases.
releases:
# Nginx-ingress
- name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.26.2
  missingFileHandler: Error
  wait: true
  values:
  - values/nginx-ingress.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/nginx-ingress.yaml"
  {{ end }}


# NFS
- name: nfs-client-provisioner
  namespace: kube-system
  labels:
    app: nfs-client-provisioner
  chart: stable/nfs-client-provisioner
  version: 1.2.6
  missingFileHandler: Error
  wait: true
  values:
{{ if eq .Environment.Name "service_cluster" }}
  - values/nfs-client-provisioner-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/nfs-client-provisioner-sc.yaml"
  {{ end }}
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/nfs-client-provisioner-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/nfs-client-provisioner-wc.yaml"
  {{ end }}
{{ end }}


# Cert-manager
- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  chart: jetstack/cert-manager
  version: v0.14.1
  missingFileHandler: Error
  wait: true
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  values:
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/cert-manager.yaml"
  {{ end }}

# Prometheus-operator
- name: prometheus-operator
  namespace: monitoring
  labels:
    app: prometheus-operator
  chart: stable/prometheus-operator
  version: 8.15.11
  missingFileHandler: Error
  needs:
  - cert-manager/cert-manager
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
{{ if eq .Environment.Name "service_cluster" }}
  - values/prometheus-operator-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-operator-sc.yaml"
  {{ end }}
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/prometheus-operator-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-operator-wc.yaml"
  {{ end }}
{{ end }}


- name: ck8sdash
  namespace: ck8sdash
  labels:
    app: ck8sdash
  chart: ./charts/ck8sdash
  version: 0.3.1
  missingFileHandler: Error
  needs:
  - cert-manager/cert-manager
  values:
  - values/ck8sdash-common.yaml.gotmpl
{{ if eq .Environment.Name "service_cluster" }}
  - values/ck8sdash-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/ck8sdash-sc.yaml"
  {{ end }}
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/ck8sdash-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/ck8sdash-wc.yaml"
  {{ end }}
{{ end }}

- name: node-local-dns
  namespace: kube-system
  labels:
    app: node-local-dns
  chart: ./charts/node-local-dns
  version: 0.1.0
  missingFileHandler: Error
  values:
  - values/node-local-dns.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/node-local-dns.yaml"
  {{ end }}

# metrics-server
- name: metrics-server
  namespace: kube-system
  labels:
    app: metrics-server
  chart: stable/metrics-server
  version: 2.10.0
  missingFileHandler: Error
  values:
  - values/metrics-server.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/metrics-server.yaml"
  {{ end }}


# Service cluster releases
{{ if eq .Environment.Name "service_cluster" }}
# Dex
- name: dex
  namespace: dex
  labels:
    app: dex
  chart: stable/dex
  version: 2.5.0
  missingFileHandler: Error
  wait: true
  needs:
  - cert-manager/cert-manager
  values:
  - values/dex.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/dex.yaml"
  {{ end }}


# Prometheus-instance for scraping workload cluster metrics
- name: wc-scraper
  namespace: monitoring
  labels:
    app: wc-scraper
  chart: ./charts/prometheus-instance
  version: 0.1.0
  missingFileHandler: Error
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  needs:
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
  - values/prometheus-wc-federate-scraper.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-wc-federate-scraper.yaml"
  {{ end }}

# prometheus wc-scraper alerts
- name: wc-scraper-alerts
  namespace: monitoring
  labels:
    app: prometheus-alerts
    prometheus: wc-scraper
  chart: ./charts/prometheus-alerts
  version: 0.1.0
  missingFileHandler: Error
  values:
{{ if eq .Environment.Name "service_cluster" }}
  # Note: we want to have alerts for WC since this is wc-scraper, even if it is
  # running in SC.
  - values/prometheus-alerts-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-alerts-wc.yaml"
  {{ end }}
{{ end }}

# prometheus sc-alerts
- name: sc-alerts
  namespace: monitoring
  labels:
    app: prometheus-alerts
    prometheus: sc
  chart: ./charts/prometheus-alerts
  version: 0.1.0
  missingFileHandler: Info
  values:
  - values/prometheus-alerts-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-alerts-sc.yaml"
  {{ end }}


{{ if eq (env "ENABLE_CUSTOMER_GRAFANA") "true" }}
# Grafana instance for customer
- name: customer-grafana
  namespace: monitoring
  labels:
    app: customer-grafana
    app.kubernetes.io/instance: customer-grafana
    app.kubernetes.io/name: grafana
  chart: stable/grafana
  version: 5.3.4
  missingFileHandler: Error
  needs:
  - cert-manager/cert-manager
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
  - values/grafana-customer.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/grafana-customer.yaml"
  {{ end }}
{{ end }}


# Elasticsearch-operator
- name: elasticsearch-operator
  namespace: elastic-system
  labels:
    app: elasticsearch-operator
  chart: ./charts/elasticsearch-operator
  version: 0.1.0
  missingFileHandler: Error
  wait: true
  needs:
  - cert-manager/cert-manager
  {{ if eq (env "ES_STORAGE_CLASS") "local-storage" }}
  - kube-system/local-volume-provisioner
  {{ end }}
  values:
  - values/elasticsearch-operator.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/elasticsearch-operator.yaml"
  {{ end }}


# Local volume provisioner
- name: local-volume-provisioner
  namespace: kube-system
  labels:
    app: local-volume-provisioner
  chart: ./charts/local-volume-provisioner
  version: 2.3.4
  missingFileHandler: Info
  values:
  - values/local-volume-provisioner.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/local-volume-provisioner.yaml"
  {{ end }}


# Elasticsearch
- name: elasticsearch
  namespace: elastic-system
  labels:
    app: elasticsearch
  chart: ./charts/elasticsearch
  version: 0.1.0
  missingFileHandler: Error
  needs:
  - elastic-system/elasticsearch-operator
  - cert-manager/cert-manager
  values:
  - values/elasticsearch.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/elasticsearch.yaml"
  {{ end }}


#Elasticsearch-prometheus-exporter
- name: elasticsearch-prometheus-exporter
  namespace: elastic-system
  labels:
    app: elasticsearch-prometheus-exporter
  chart: stable/elasticsearch-exporter
  version: 2.1.1
  missingFileHandler: Error
  needs:
  - elastic-system/elasticsearch
  values:
  - values/elasticsearch-prometheus-exporter.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/elasticsearch-prometheus-exporter.yaml"
  {{ end }}


# configure elasticsearch
- name: configure-es
  namespace: elastic-system
  labels:
    app: config
  chart: ./charts/configure-es
  version: 0.1.0
  missingFileHandler: Error
  needs:
  - elastic-system/elasticsearch
  values:
  - values/configure-es.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/configure-es.yaml"
  {{ end }}


# Harbor
- name: harbor-certs
  namespace: harbor
  labels:
    app: harbor
  chart: ./charts/harbor-certs
  version: 0.1.0
  missingFileHandler: Error
  needs:
  - cert-manager/cert-manager
  values:
  - values/harbor-certs.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/harbor-certs.yaml"
  {{ end }}


- name: harbor
  namespace: harbor
  labels:
    app: harbor
  chart: harbor/harbor
  version: 1.4.0
  missingFileHandler: Error
  wait: true
  timeout: 600
  needs:
  - cert-manager/cert-manager
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
  - values/harbor.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/harbor.yaml"
  {{ end }}


- name: init-harbor
  namespace: harbor
  labels:
    app: harbor
  chart: ./charts/init-harbor
  version: 0.1.0
  missingFileHandler: Error
  needs:
  - harbor/harbor
  values:
  - values/init-harbor.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/init-harbor.yaml"
  {{ end }}

- name: harbor-backup
  namespace: harbor
  labels:
    app: harbor
    component: backup
  chart: ./charts/harbor-backup
  version: 0.1.0
  missingFileHandler: Error
  values:
  - values/harbor-backup.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/harbor-backup.yaml"
  {{ end }}


# InfluxDB with disk usage monitoring and metrics retention
- name: influxdb
  namespace: influxdb-prometheus
  labels:
    app: influxdb
  chart: elastisys/influxdb
  version: 4.8.1
  missingFileHandler: Error
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  needs:
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
  - values/influxdb.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/influxdb.yaml"
  {{ end }}

- name: blackbox
  namespace: monitoring
  labels:
    app: blackbox
  chart: ./charts/blackbox
  version: 0.1.0
  missingFileHandler: Error
  values:
  - values/blackbox.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/blackbox.yaml"
  {{ end }}

# Fluentd
- name: fluentd
  namespace: fluentd
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: Error
  values:
  - values/fluentd-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/fluentd-sc.yaml"
  {{ end }}


# Fluentd aggregator
- name: fluentd-aggregator
  namespace: fluentd
  labels:
    app: fluentd-aggregator
  chart: stable/fluentd
  version: 2.3.2
  missingFileHandler: Error
  {{ if eq (env "STORAGE_CLASS") "nfs-client" }}
  needs:
  - kube-system/nfs-client-provisioner
  {{ end }}
  values:
  - values/fluentd-aggregator.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/fluentd-aggregator.yaml"
  {{ end }}


# Velero
- name: velero
  namespace: velero
  labels:
    app: velero
  chart: vmware-tanzu/velero
  version: 2.8.2
  missingFileHandler: Error
  values:
  - values/velero-sc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/velero-sc.yaml"
  {{ end }}


# End of system services releases
{{ end }}

# Workload cluster releases
{{ if eq .Environment.Name "workload_cluster"  }}
{{ if eq (env "ENABLE_FALCO") "true" }}
# Falco
- name: falco
  namespace: falco
  labels:
    app: falco
  chart: stable/falco
  version: 1.1.6
  missingFileHandler: Error
  values:
  - values/falco.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/falco.yaml"
  {{ end }}
{{ end }}

#Basic auth credentials for accessing workload cluster prometheus
- name: prometheus-auth
  namespace: monitoring
  labels:
    app: prometheus-auth
  chart: ./charts/basic-auth-secret
  version: 0.1.0
  missingFileHandler: Error
  values:
  - values/prometheus-auth.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-auth.yaml"
  {{ end }}

{{ if eq (env "ENABLE_CUSTOMER_ALERTMANAGER") "true" }}
- name: customer-alertmanager
  namespace: monitoring
  labels:
    app: customer-alertmanager
  chart: ./charts/examples/customer-alertmanager
  version: 0.1.0
  missingFileHandler: Error
  needs:
  - cert-manager/cert-manager
  values:
  - values/customer-alertmanager.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/customer-alertmanager.yaml"
  {{ end }}
{{ end }}

{{ if eq (env "ENABLE_FALCO_ALERTS") "true" }}
- name: falcosidekick
  namespace: falco
  labels:
    app: falco
  chart: ./charts/falcosidekick
  version: 0.1.14
  missingFileHandler: Error
  values:
  - values/falcosidekick.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/falcosidekick.yaml"
  {{ end }}
{{ end }}

# Fluentd
- name: fluentd-system
  namespace: kube-system
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: Error
  values:
  - values/fluentd-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/fluentd-wc.yaml"
  {{ end }}


# Fluentd configurable by the customer
- name: fluentd
  namespace: fluentd
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 5.1.1
  missingFileHandler: Error
  values:
  - values/fluentd-customer.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/fluentd-customer.yaml"
  {{ end }}


{{ if eq (env "ENABLE_OPA") "true" }}
# gatekeeper-operator
- name: gatekeeper-operator
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-operator
  chart: ./charts/gatekeeper-operator
  version: 1.6.0
  missingFileHandler: Error
  wait: true
  values:
  - values/gatekeeper-operator.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/gatekeeper-operator.yaml"
  {{ end }}


# gatekeeper-templates
- name: gatekeeper-templates
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-templates
  chart: ./charts/gatekeeper-templates
  version: 1.6.0
  missingFileHandler: Error
  needs:
  - gatekeeper-system/gatekeeper-operator
  values:
  - values/gatekeeper-templates.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/gatekeeper-templates.yaml"
  {{ end }}


# gatekeeper-constraints
- name: gatekeeper-constraints
  namespace: gatekeeper-system
  labels:
    app: gatekeeper-constraints
  chart: ./charts/gatekeeper-constraints
  version: 1.6.0
  missingFileHandler: Error
  needs:
  - gatekeeper-system/gatekeeper-templates
  values:
  - values/gatekeeper-constraints.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/gatekeeper-constraints.yaml"
  {{ end }}
{{ end }}


# Velero
- name: velero
  namespace: velero
  labels:
    app: velero
  chart: vmware-tanzu/velero
  version: 2.8.2
  missingFileHandler: Error
  values:
  - values/velero-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/velero-wc.yaml"
  {{ end }}

# TODO: Make this optional! Customers may not want any alerts by default.
# It should also be separate from the alerts we use. Customers should not need
# to care about system components that they cannot touch anyway.
# prometheus customer-alerts
- name: ck8s-alerts
  namespace: monitoring
  labels:
    app: prometheus-alerts
  chart: ./charts/prometheus-alerts
  version: 0.1.0
  missingFileHandler: Info
  values:
  - values/prometheus-alerts-wc.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/prometheus-alerts-wc.yaml"
  {{ end }}

# Customer RBAC
- name: customer-rbac
  namespace: kube-system
  labels:
    app: customer-rbac
  chart: ./charts/customer-rbac
  version: 0.1.0
  missingFileHandler: Error
  {{ if eq (env "ENABLE_OPA") "true" }}
  needs:
  - gatekeeper-system/gatekeeper-constraints
  {{ end }}
  values:
  - values/customer-rbac.yaml.gotmpl
  {{ if env "CK8S_ADDITIONAL_VALUES" }}
  - "{{ env "CK8S_ADDITIONAL_VALUES" }}/customer-rbac.yaml"
  {{ end }}
{{ end }}
