# Chart repositories used from within this state file.
repositories:
- name: stable 
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io

# System-services specific repositories
{{ if eq .Environment.Name "system-services" }}
- name: harbor
  url: https://helm.goharbor.io
{{ end }}

# Customer specific repositories
{{ if eq .Environment.Name "customer" }}
- name: kiwigrid
  url: https://kiwigrid.github.io
{{ end }}

# Defults settings to use with helm and tiller.
helmDefaults:
  tillerNamespace: kube-system  #dedicated default key for tiller-namespace
  # defaults for verify, wait, force, timeout and recreatePods under releases[]
  # verify: true
  # wait: true
  # timeout: 600
  # recreatePods: true
  # force: true
  # enable TLS for request to Tiller
  tls: true

  # TODO: Use env instead of fixed paths for certs.

  {{ if eq .Environment.Name "system-services" }}
  # path to TLS CA certificate file (default "$HELM_HOME/ca.pem")
  tlsCACert: "../certs/system-services/kube-system/certs/ca.pem"
  # path to TLS certificate file (default "$HELM_HOME/cert.pem")
  tlsCert: "../certs/system-services/kube-system/certs/helm.pem"
  # path to TLS key file (default "$HELM_HOME/key.pem")
  tlsKey: "../certs/system-services/kube-system/certs/helm-key.pem"
  {{ end }}
  {{ if eq .Environment.Name "customer" }}
  # path to TLS CA certificate file (default "$HELM_HOME/ca.pem")
  tlsCACert: "../certs/customer/kube-system/certs/ca.pem"
  # path to TLS certificate file (default "$HELM_HOME/cert.pem")
  tlsCert: "../certs/customer/kube-system/certs/helm.pem"
  # path to TLS key file (default "$HELM_HOME/key.pem")
  tlsKey: "../certs/customer/kube-system/certs/helm-key.pem"
  {{ end }}


# Environments
environments:
  customer:
  system-services:

# The desired state of Helm releases.
releases:
# NFS
- name: nfs-client-provisioner
  namespace: kube-system 
  labels:
    app: nfs-client-provisioner
  chart: stable/nfs-client-provisioner
  version: 1.2.6
  missingFileHandler: error
  wait: true
  values:
  {{ if eq .Environment.Name "system-services" }}
  - values/nfs-client-provisioner-ss.yaml.gotmpl
  {{ end }}
  {{ if eq .Environment.Name "customer" }}
  - values/nfs-client-provisioner-c.yaml.gotmpl
  {{ end }}

# Oauth2
- name: oauth2
  namespace: kube-system
  labels:
    app: oauth2
  chart: stable/oauth2-proxy
  version: 0.12.3
  missingFileHandler: error
  values:
  {{ if eq .Environment.Name "system-services" }}
    - values/oauth2-ss.yaml.gotmpl
  {{ end }}

  {{ if eq .Environment.Name "customer" }}
  - values/oauth2-c.yaml.gotmpl
  {{ end }}

# Cert-manager
- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  chart: jetstack/cert-manager
  version: v0.8.0
  missingFileHandler: error
  wait: true

# Prometheus-operator
- name: prometheus-operator
  namespace: monitoring
  labels:
    app: prometheus-operator
  chart: stable/prometheus-operator
  version: 6.2.1
  missingFileHandler: error
  values:
{{ if eq .Environment.Name "system-services" }}    
  - values/prometheus-operator.yaml.gotmpl
{{ end }}
{{ if eq .Environment.Name "customer" }}
  - values/prometheus-operator-c.yaml.gotmpl
{{ end }}

# System services releases
{{ if eq .Environment.Name "system-services" }}
# Dex
- name: dex
  namespace: dex
  labels:
    app: dex
  chart: stable/dex
  version: 1.4.0
  missingFileHandler: error
  values:
  - ../charts/dex/values.yaml
  - values/dex.yaml.gotmpl

# Harbor
- name: harbor
  namespace: harbor
  labels:
    app: harbor
  chart: harbor/harbor
  version: 1.1.1
  missingFileHandler: error
  wait: true
  values:
  - values/harbor.yaml.gotmpl

# InfluxDB
- name: influxdb
  namespace: influxdb-prometheus
  labels:
    app: influxdb
  chart: stable/influxdb
  version: 1.3.1
  missingFileHandler: error
  values:
  - values/influxdb.yaml.gotmpl

# Prometheus-operator (customer reader - remove at some point!)
- name: prometheus-operator-c-reader
  namespace: customer-monitoring
  labels:
    app: prometheus-operator-c-reader
  chart: stable/prometheus-operator
  version: 6.2.1
  missingFileHandler: error
  values:
  - values/prometheus-operator-c-reader.yaml.gotmpl
{{ end }}

# Customer releases
{{ if eq .Environment.Name "customer"  }}
# Falco
- name: falco
  namespace: falco
  labels:
    app: falco
  chart: stable/falco
  version: 0.7.6
  missingFileHandler: error

# Fluentd
- name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
  chart: kiwigrid/fluentd-elasticsearch
  version: 4.5.1
  missingFileHandler: error
  values:
  - values/fluentd.yaml.gotmpl

# opa
- name: opa
  namespace: opa
  labels:
    app: opa
  chart: stable/opa
  version: 1.6.0
  missingFileHandler: error
  values:
  - values/opa.yaml.gotmpl
{{ end }}
