repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
    - id: go-fmt
# Enable when go modules are supported.
#    - id: go-vet
# Enable when we have proper comments everywhere.
#    - id: go-lint
    - id: go-imports
