kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp2-prod
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
