apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-du-monitoring-cronjob
  namespace: influxdb-prometheus
data:
  cronjob: |
    ### cron file for running the export script
    {{ .Values.monitoring.cronSchedule }} root sh /scripts/export-influxdb-database-size.sh ## run the export script
    # An empty line is required at the end of this file for a valid cron file.