apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-script
  namespace: {{ .Release.Namespace }}
data:
  export-influxdb-database-size.sh: |
    #!/bin/sh
    
    echo influxdb_{{ .Values.influxdb.databaseName }}_size $(du -s /var/lib/influxdb/data/{{ .Values.influxdb.databaseName }} | cut -f 1) > /textfile-collector/influxdb_{{ .Values.influxdb.databaseName }}_size.prom.$$
    mv /textfile-collector/influxdb_{{ .Values.influxdb.databaseName }}_size.prom.$$ /textfile-collector/influxdb_{{ .Values.influxdb.databaseName }}_size.prom