apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: influxdb-prometheus
  labels:
    app: influxdb-du-monitoring
    release: prometheus-operator
spec:
  selector:
    app: influxdb-du-monitoring
  ports:
    - name: web
      port: 9100
      protocol: TCP
      targetPort: 9100