9:
  action: delete_indices
  description: "Clean up the oldest postgresql-* indices that exceeds total disk space ${POSTGRESQL_RETENTION_SIZE} GB"
  options:
    continue_if_exception: False
    ignore_empty_list: True
    allow_ilm_indices: True
  filters:
  # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
  - filtertype: pattern
    kind: regex
    value: 'postgresql-*'
  - filtertype: space
    disk_space: ${POSTGRESQL_RETENTION_SIZE}
    use_age: True
    source: name
    timestring: '%Y.%m.%d'
  - filtertype: kibana
    exclude: True
10:
  action: delete_indices
  description: "Clean up the postgresql-* indices that are older then ${POSTGRESQL_RETENTION_AGE} days"
  options:
    continue_if_exception: False
    ignore_empty_list: True
    allow_ilm_indices: True
  filters:
  # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
  - filtertype: pattern
    kind: regex
    value: 'postgresql-*'
  - filtertype: age
    source: name
    direction: older
    timestring: '%Y.%m.%d'
    unit: days
    unit_count: ${POSTGRESQL_RETENTION_AGE}
  - filtertype: kibana
    exclude: True
