apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.5.2
  nodeSets:
  - count: {{ .Values.elasticsearch.node.count }}
    name: nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      plugin.mandatory: repository-s3
      s3.client.default.endpoint: {{ .Values.elasticsearch.s3.endpoint }}
      s3.client.default.protocol: https
      s3.client.default.path_style_access: true
      action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*,.monitoring-*"
      xpack.security.authc.realms.native.native1.order: 0
    podTemplate:
      spec:
        initContainers:
        - name: install-s3-plugin
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        containers:
        - name: elasticsearch
          {{- with .Values.elasticsearch.env }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.elasticsearch.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.elasticsearch.affinity }}
        affinity:
{{ toYaml . | indent 10 }}
          {{- end }}
          {{- with .Values.elasticsearch.tolerations }}
        tolerations:
{{ toYaml . | indent 10 }}
          {{- end }}          
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storageSize }}
        storageClassName: {{ .Values.elasticsearch.storageClassName }}
  secureSettings:
  - secretName: s3-credentials
