apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.5.2
  nodeSets:
  - count: 3
    name: nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      plugin.mandatory: repository-s3
      s3.client.default.endpoint: {{ .Values.elasticsearch.s3.endpoint }}
      s3.client.default.protocol: https
      s3.client.default.path_style_access: true
      xpack.security.authc.realms.native.native1.order: 0
    podTemplate:
      spec:
        initContainers:
        - name: install-s3-plugin
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        containers:
        - name: elasticsearch
          resources:
{{ toYaml .Values.elasticsearch.resources | indent 12 }}
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: common.k8s.elastic.co/type
                    operator: In
                    values:
                    - elasticsearch
                topologyKey: "kubernetes.io/hostname"

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storageSize }}
        storageClassName: {{ .Values.elasticsearch.storageClassName }}
  secureSettings:
  - secretName: s3-credentials
