apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.5.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        {{- with .Values.kibana.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
