# The images will export data with jmx exporter to port 8080
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjar-deployment
  labels:
    app: custom-jar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-jar
  template:
    metadata:
      labels:
        app: custom-jar
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: custom-javajar
        image: erikgunne/rep:testjar
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "225Mi"
            cpu: "100m"
