apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-jar-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      name: customer-jar-service
  endpoints:
  - port: jar-port