apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-jar-monitor
  labels:
    scrape: "true"
spec:
  selector:
    matchLabels:
      name: custom-jar-service
  endpoints:
  - port: jar-port
