apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-c-reader
  name: prometheus-c-reader
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    key: prometheus-federate-additional.yaml
    name: prometheus-c-scrape-configs

  # alerting:
  #   alertmanagers: []
  enableAdminAPI: false
  # listenLocal: false
  logFormat: logfmt
  logLevel: info
  remoteRead:
  - read_recent: true
    url: http://influxdb-prometheus.influxdb-prometheus.svc.cluster.local:8086/api/v1/prom/read?db=customer2&u=demo&p=demo-pass
  remoteWrite:
  - url: http://influxdb-prometheus.influxdb-prometheus.svc.cluster.local:8086/api/v1/prom/write?db=customer2&u=demo&p=demo-pass
  replicas: 1
  retention: 10d
  # routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-operator-prometheus
  serviceMonitorSelector:
    matchLabels:
      target: none  # so that operator wont generate new config