apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-admin
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${CUSTOMER_USER}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: customer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customer-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${CUSTOMER_USER}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${CUSTOMER_USER}