ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - dex.demo.compliantk8s.com
  tls:
    - secretName: dex-example-tls
      hosts:
        - dex.demo.compliantk8s.com

certs:
  web:
    create: false
  grpc:
    create: true

config:
  issuer: https://dex.demo.compliantk8s.com
  web:
    http: 0.0.0.0:8080
  connectors:

  staticClients:
    - id: kubernetes
      redirectURIs:
        - 'http://localhost:8000'
        - 'https://dashboard.demo.compliantk8s.com/oauth2/callback'
      name: 'Kubernetes dashboard'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  enablePasswordDB: true
  staticPasswords:
    - email: "admin@example.com"
      # bcrypt hash of the string "password"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
