apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  namespace: test
spec:
  containers:
  - name: private-reg-container
    image: core.harbor.demo.compliantk8s.com/test/nginx:test-01
  imagePullSecrets:
  - name: regcred
