apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "elasticsearch-slm.fullname" . }}
  labels:
    {{- include "elasticsearch-slm.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "elasticsearch-slm.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: run
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command: ['/bin/bash']
              args: ['/scripts/slm-retention.bash']
              {{- if .Values.resources }}
              resources: {{- toYaml .Values.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: {{ .Values.esEndpoint }}
                - name: SNAPSHOT_REPOSITORY
                  value: {{ .Values.snapshotRepository }}
                - name: MIN_SNAPSHOTS
                  value: {{ .Values.snapshots.min | quote }}
                - name: MAX_SNAPSHOTS
                  value: {{ .Values.snapshots.max | quote }}
                - name: MAX_AGE_SECONDS
                  value: {{ .Values.snapshots.maxAgeSeconds | quote }}
                - name: ELASTICSEARCH_API_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.snapshotApiAccountSecret }}
                      key: username
                - name: ELASTICSEARCH_API_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.snapshotApiAccountSecret }}
                      key: password
          volumes:
          - name: scripts
            configMap:
              name: {{ include "elasticsearch-slm.fullname" . }}
          securityContext:
            runAsUser: 65534
