cloud_provider_config:
  username: "{{ lookup('env', 'OS_USERNAME') | default(omit) }}"
  password: "{{ lookup('env', 'OS_PASSWORD') | default(omit) }}"
  auth_url: "{{ lookup('env', 'OS_AUTH_URL') | default(omit) }}"
  tenant_id: "{{ lookup('env', 'OS_PROJECT_ID') | default(omit) }}"
  domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') | default(omit) }}"
calico_version: v3.11
