apiVersion: v1
kind: Pod
metadata:
  name: influxdb-restore
  labels:
    app: influxdb-backup
spec:
  restartPolicy: Never
  volumes:
  - name: backups
    emptyDir: {}
  initContainers:
  - name: aws-cli-util
    image: atlassian/pipelines-awscli
    command:
    - /bin/sh
    args:
    - '-c'
    - |
      printenv
      aws s3 --endpoint-url $S3_REGION_ENDPOINT sync "$S3_INFLUX_BUCKET_URL/$INFLUX_BACKUP_NAME" /backups/$INFLUX_BACKUP_NAME 
    env:
    - name: AWS_DEFAULT_REGION
      value: $S3_REGION
    - name: AWS_SECRET_ACCESS_KEY
      value: $S3_SECRET_KEY
    - name: AWS_ACCESS_KEY_ID
      value: $S3_ACCESS_KEY

    volumeMounts:
    - name: backups
      mountPath: /backups
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 300Mi
  containers:
  - name: influxdb-restore
    image: influxdb:1.7.6-alpine
    volumeMounts:
    - name: backups
      mountPath: /backups
    command:
    - /bin/sh
    args:
    - '-c'
    - |
      influxd restore -portable -host $INFLUX_ADDR /backups/$INFLUX_BACKUP_NAME/
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 300Mi
