apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        image: mongo
        securityContext:
          runAsUser: 1000
        command: ['sh', '-c',
         'until mongo mongodb://mongo.mongo --eval "print(\"waited for connection\")";
         do sleep 5; done;']
      containers:
        - name: backend
          image: vanneback/test-app-backend:latest
          securityContext:
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: DB_DNS
              value: "mongodb://mongo.mongo:27017/jelotest"
