apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: harbor-core-cert
  namespace: harbor
spec:
  secretName: harbor-core-cert
  commonName: "harbor.${ECK_SS_DOMAIN}"
  isCA: false
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer