apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - default-deny.yaml

namespace: mongo
commonLabels:
  app.kubernetes.io/name: mongo
