apiVersion: templates.gatekeeper.sh/v1alpha1
kind: ConstraintTemplate
metadata:
  name: k8sresourcerequests
spec:
  crd:
    spec:
      names:
        kind: K8sResourceRequests
        listKind: K8sResourceRequestsList
        plural: k8sresourcerequests
        singular: k8sresourcerequests
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{ .Files.Get "policies/resource-requests.rego"  | indent 8 }}
