apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: harbor-core-cert
  namespace: {{ .Release.namespace }}
spec:
  secretName: harbor-core-cert
  commonName: {{ .Values.core.domain }}
  isCA: false
  issuerRef:
    name: selfsigning-issuer
    kind: Issuer
