apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: |
   {{ htpasswd .Values.basic_auth.username .Values.basic_auth.password }}
