apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dex:privileged
  namespace: dex
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex:privileged
  namespace: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex:privileged
subjects:
- kind: ServiceAccount
  name: dex
  namespace: dex
  