apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-system:default-psp
  namespace: elastic-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-system:default-psp
  namespace: elastic-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elastic-system:default-psp
subjects:
- kind: ServiceAccount
  name: elasticsearch-client
  namespace: elastic-system
- kind: ServiceAccount
  name: default
  namespace: elastic-system
- kind: ServiceAccount
  name: elasticsearch-master
  namespace: elastic-system
- kind: ServiceAccount
  name: elasticsearch-data
  namespace: elastic-system
- kind: ServiceAccount
  name: elastic-operator
  namespace: elastic-system
  