apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: influxdb-prometheus:default-psp
  namespace: influxdb-prometheus
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: influxdb-prometheus:default-psp
  namespace: influxdb-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: influxdb-prometheus:default-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: influxdb-prometheus
  