apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequirenetworkpolicy
spec:
  crd:
    spec:
      names:
        kind: K8sRequireNetworkPolicy
        listKind: K8sRequireNetworkPolicyList
        plural: k8sRequireNetworkPolicy
        singular: k8sRequireNetworkPolicy
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{ .Files.Get "policies/network-policies.rego"  | indent 8 }}
