apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-webhook-service
  namespace: gatekeeper-system
spec:
  selector:
    app: GATEKEEPER_APP_LABEL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
spec:
  replicas: HELMSUBST_DEPLOYMENT_REPLICAS
  selector:
    matchLabels:
      app: gatekeeper-operator
      release: RELEASE_NAME
  template:
    spec:
      containers:
        - name: manager
          args:
            - --audit-interval={{ .Values.auditInterval }}
            - --port=8443
            - --logtostderr
            - --constraint-violations-limit={{ .Values.constraintViolationsLimit }}
            - --audit-from-cache={{ .Values.auditFromCache }}
            - --exempt-namespace=gatekeeper-system
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.release }}"
          resources: HELMSUBST_DEPLOYMENT_CONTAINER_RESOURCES
      nodeSelector: HELMSUBST_DEPLOYMENT_POD_SCHEDULING
