# Default values for elasticsearch-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kibana:
  ingress:
    host: kibana.example.com
    issuer: letsencrypt-staging
  resources: {}
    # requests:
    #   memory: 1Gi
    #   cpu: 0.5
    # limits:
    #   memory: 2Gi
    #   cpu: 2

elasticsearch:
  ingress:
    host: elastic.example.com
    issuer: letsencrypt-staging
  s3:
    endpoint: https://s3.example.com
    access_key: replace-me
    secret_key: replace-me
  storageClassName: nfs-client
  storageSize: 40Gi
  env: []
    # - name: ES_JAVA_OPTS
    #   value: -Xms2g -Xmx2g
  resources: {}
    # requests:
    #   memory: 2Gi
    #   cpu: 0.3
    # limits:
    #   memory: 3Gi
    #   cpu: 1

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: common.k8s.elastic.co/type
              operator: In
              values:
              - elasticsearch
          topologyKey: "kubernetes.io/hostname"

  tolerations: []


curator:
  retention:
    other_gb: 1
    other_days: 10
    kubecomponents_gb: 1
    kubecomponents_days: 10
    kubernetes_gb: 1
    kubernetes_days: 10
    kubeaudit_gb: 100
    kubeaudit_days: 30
    postgresql_gb: 30
    postgresql_days: 30
  # Should curator clean up the postgresql indices?
  postgresql: false
