- job_name: 'federate'
  scrape_interval: 15s

  honor_labels: true
  metrics_path: '/federate'

  scheme: https

  params:
    'match[]':
      - '{job="kubelet"}'
      - '{job="kube-state-metrics"}'
      - '{job="node-exporter"}'
      - '{job="coredns"}'
      - '{job="apiserver"}'
      - '{__name__=~"job:.*"}'
      - '{__name__=~"namespace(_|:).*"}'

  tls_config:
    insecure_skip_verify: ${TLS_SKIP_VERIFY}

  static_configs:
    - labels:
        cluster: customer
      targets:
      - prometheus.${ECK_WC_DOMAIN}