{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.issuer.selfSigned -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
{{- end }}
{{- end }}
