apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "prometheus-instance.fullname" . }}
  labels:
{{ include "prometheus-instance.labels" . | indent 4 }}
spec:
{{- if .Values.scrapeConfig }}
  additionalScrapeConfigs:
    key: federate-scrape-config.yaml
    name: {{ include "prometheus-instance.fullname" . }}
{{- end }}
{{- toYaml .Values.prometheusSpec | nindent 2 }}
