{{- define "prometheus-instance.scrape-config" }}
{{- toYaml .Values.scrapeConfig }}
{{- end }}
{{- if .Values.scrapeConfig }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prometheus-instance.fullname" . }}
data:
  federate-scrape-config.yaml: {{ include "prometheus-instance.scrape-config" . | b64enc }}
{{- end }}
