apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-instance.fullname" . }}
  labels:
{{ include "prometheus-instance.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: web
      protocol: TCP
      name: web
  selector:
    prometheus: {{ include "prometheus-instance.fullname" . }}
