{{- $labels := .Values.labels }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter-{{ .name }}
  labels:
{{ $labels | toYaml | indent 4 }}
spec:
  endpoints:
  - port: http
    scheme: http
    path: "/probe"
    interval: {{ .interval }}
    scrapeTimeout: {{ .scrapeTimeout }}
    params:
      module:
      - {{ .module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: name
        replacement: {{ .name }}
      - targetLabel: target
        replacement: {{ .url }}
  jobLabel: blackbox-{{ .name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: blackbox
  namespaceSelector:
    matchNames:
      - {{ $namespace }}
{{- end }}
