# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Todo name field not integrated
backend:
  name: backend
  namespace: test
  image: vanneback/test-app-backend
  tag: latest
  pullPolicy: Always

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 3001

frontend:
  name: frontend
  namespace: test
  image: vanneback/test-app-frontend
  tag: latest
  pullPolicy: Always

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

mongo:
  name: mongo
  namespace: test
  #image: vanneback/test-app-database
  image: mongo
  tag: latest
  pullPolicy: IfNotPresent

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 27017

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi

ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: demo.compliantk8s.com
    path: /

  ## The tls configuration for the ingress
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  tls:
    - secretName: demo-certs
      hosts:
        - demo.compliantk8s.com
