apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-buckets
  labels:
    app: sync-buckets
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sync-buckets
        spec:
          restartPolicy: Never
          volumes:
          - name: rclone-config
            secret:
              secretName: rclone-config
          containers:
          - name: rclone
            image: elastisys/rclone-sync:1.0.0
            env:
            - name: BUCKETS_TO_SYNC
              value: "psql-tempus-safespring-ck8s influxdb-tempus-safespring-ck8s elasticsearch-tempus-safespring-ck8s velero-tempus-safespring-ck8s"
            - name: REMOTE_SRC
              value: "safespring-sto2"
            - name: REMOTE_DST
              value: "safespring-osl1"
            - name: EXTRA_ARGS
              value: "--progress"
            volumeMounts:
            - name: rclone-config
              mountPath: /root/.config/rclone/
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 2000m
                memory: 4000Mi
