apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name  }}-backend
  labels:
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: backend
  namespace: {{ .Values.backend.namespace }}
spec:
  # Only allow traffic from frontend Pods
  podSelector: 
    matchLabels: 
      component: backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: frontend