apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "elasticsearch-backup.fullname" . }}
  labels:
    {{- include "elasticsearch-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "elasticsearch-backup.labels" . | nindent 12 }}
        spec:
          containers:
          - name: snapshotter
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.resources }}
            resources: {{- toYaml .Values.resources | nindent 14 }}
            {{- end }}
            volumeMounts:
              - name: scripts
                mountPath: /scripts
            env:
              - name: ELASTICSEARCH_ENDPOINT
                value: {{ .Values.esEndpoint | quote }}
              - name: SNAPSHOT_REPOSITORY
                value: {{ .Values.snapshotRepository | quote }}
              - name: INDICES
                value: {{ .Values.indices | quote }}
              - name: ELASTICSEARCH_API_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.snapshotApiAccountSecret }}
                    key: username
              - name: ELASTICSEARCH_API_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.snapshotApiAccountSecret }}
                    key: password
            command: ['/bin/bash']
            args: ['/scripts/backup.sh']
          volumes:
          - name: scripts
            configMap:
              name: {{ include "elasticsearch-backup.fullname" . }}
          restartPolicy: {{ .Values.restartPolicy }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          securityContext:
            runAsUser: 65534
