apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-script
  namespace: {{ .Release.Namespace }}
data:
  influxdb-size-based-metrics-retention.py: |
{{ .Files.Get "influxdb_size_based_metrics_retention.py" | indent 4}}