resources:
  - cronjob.yaml

configMapGenerator:
- name: influxdb-metrics-retention-script
  files:
    - influxdb_size_based_metrics_retention.py

secretGenerator:
- name: influxdb-auth
  envs:
  - secret.env