apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8sallowedrepos.constraints.gatekeeper.sh
spec:
  conversion:
    strategy: None
  group: constraints.gatekeeper.sh
  names:
    categories:
    - constraint
    kind: K8sAllowedRepos
    listKind: K8sAllowedReposList
    plural: k8sallowedrepos
    singular: k8sallowedrepos
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            enforcementAction:
              type: string
            match:
              properties:
                excludedNamespaces:
                  items:
                    type: string
                  type: array
                kinds:
                  items:
                    properties:
                      apiGroups:
                        items:
                          type: string
                      kinds:
                        items:
                          type: string
                  type: array
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaces:
                  items:
                    type: string
                  type: array
            parameters:
              properties:
                repos:
                  items:
                    type: string
                  type: array
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---    
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8srequirenetworkpolicy.constraints.gatekeeper.sh
spec:
  conversion:
    strategy: None
  group: constraints.gatekeeper.sh
  names:
    categories:
    - constraint
    kind: K8sRequireNetworkPolicy
    listKind: K8sRequireNetworkPolicyList
    plural: k8srequirenetworkpolicy
    singular: k8srequirenetworkpolicy
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            enforcementAction:
              type: string
            match:
              properties:
                excludedNamespaces:
                  items:
                    type: string
                  type: array
                kinds:
                  items:
                    properties:
                      apiGroups:
                        items:
                          type: string
                      kinds:
                        items:
                          type: string
                  type: array
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaces:
                  items:
                    type: string
                  type: array
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8sresourcerequests.constraints.gatekeeper.sh
spec:
  conversion:
    strategy: None
  group: constraints.gatekeeper.sh
  names:
    categories:
    - constraint
    kind: K8sResourceRequests
    listKind: K8sResourceRequestsList
    plural: k8sresourcerequests
    singular: k8sresourcerequests
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            enforcementAction:
              type: string
            match:
              properties:
                excludedNamespaces:
                  items:
                    type: string
                  type: array
                kinds:
                  items:
                    properties:
                      apiGroups:
                        items:
                          type: string
                      kinds:
                        items:
                          type: string
                  type: array
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            enum:
                            - In
                            - NotIn
                            - Exists
                            - DoesNotExist
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                      type: array
                namespaces:
                  items:
                    type: string
                  type: array
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
