apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: influxdb-metrics-retention-cronjob
  labels:
    app: influxdb-metrics-retention
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: influxdb-metrics-retention
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: python-script
              configMap:
                name: influxdb-metrics-retention-script
          containers:
            - name: influxdb-metrics-retention
              image: elastisys/influxdb-metrics-retention:latest
              command: ["python3", "/app/influxdb_size_based_metrics_retention.py"]
              env:
              - name: INFLUXDB_HOST
                value: influxdb
              - name: INFLUXDB_PORT
                value: "8086"
              - name: INFLUXDB_USER
                valueFrom:
                  secretKeyRef:
                    name: influxdb-metrics-retention-env
                    key: influxdb-username
              - name: INFLUXDB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: influxdb-metrics-retention-env
                    key: influxdb-password
              - name: INFLUXDB_DATABASE
                value: service_cluster
              - name: INFLUXDB_MIN_SHARDS
                value: "1"
              - name: INFLUXDB_DATABASE_SIZE_LIMIT
                value: "5000000"
              - name: PROMETHEUS_HOST
                value: prometheus-operator-prometheus.monitoring
              - name: PROMETHEUS_PORT
                value: "9090"
              - name: PROMETHEUS_INFLUXDB_METRIC
                value: influxdb_service_cluster_size
              - name: LOGLEVEL
                value: "INFO"
              volumeMounts:
                - name: python-script
                  mountPath: /app
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 250m
                  memory: 500Mi            