apiVersion: v1
kind: ServiceAccount
metadata:
  name: ck8sdash
  namespace: ck8sdash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ck8sdash-secret-creator
  namespace: ck8sdash
rules:
- apiGroups:
  - ""
  resourceNames:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - "ck8sdash-grafana-api-key"
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ck8sdash-secret-creator
  namespace: ck8sdash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ck8sdash-secret-creator
subjects:
- kind: ServiceAccount
  name: ck8sdash