apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: elastic-system
  labels:
    app: curator
data:
  action_file.yml: |-
{{ .Files.Get "files/action_file.yml" | indent 4 }}

{{- if .Values.curator.postgresql }}
{{ .Files.Get "files/postgresql-actions.yml" | indent 6 }}
{{- end }}

  config.yml: |-
{{ .Files.Get "files/config.yml" | indent 4 }}
