global:
  enabled: true
  image: "vault:1.2.2"
  tlsDisable: false

server:
  extraVolumes:
  - type: secret
    name: vault
  
  standalone:
    enabled: true
    config: |
      ui = true

      log_level = "debug"

      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"

        tls_cert_file = "/vault/userconfig/vault/tls.crt"
        tls_key_file  = "/vault/userconfig/vault/tls.key"
      }
      
      storage "file" {
        path = "/vault/data"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: nfs-client
    accessMode: ReadWriteOnce

# This creates a service for vault ui.
# The ui needs to be enabled in the vault config.
ui:
  enabled: true
  serviceType: NodePort
