apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongo
spec:
  # Only allow traffic from the backend namespace
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mongo
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: backend
