apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ck8sdash.fullname" . }}-config
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
data:
  config.yaml: |
    port: {{ .Values.server.port }}
    grafana:
      datasource: {{ .Values.grafana.datasource }}
      url: {{ .Values.grafana.url }}
      dashboards:
        pods: kubernetes-compute-resources-pod
        workloads: kubernetes-compute-resources-workload
        persistentVolumes: kubernetes-persistent-volumes
        namespaces: kubernetes-compute-resources-namespace-workloads
        nodes: nodes
        cluster: kubernetes-compute-resources-cluster
    harbor:
      username: {{ .Values.harbor.username }}
      url: {{ .Values.harbor.url }}
    elastic:
      url: {{ .Values.elastic.url }}
      index:
        kubernetes: {{ .Values.elastic.kubernetesIndexPrefix }}
        components: {{ .Values.elastic.componentsIndexDefault }}
    kibana:
      url: {{ .Values.kibana.url }}
    oidc:
      url: {{ .Values.oidc.url }}
      clientID: {{ .Values.oidc.clientId }}
    falco:
      enable: {{ .Values.falco.enabled }}
    opa:
      enable: {{ .Values.opa.enabled }}
    info:
      elastisys:
        header: Welcome
        body: Welcome to CK8SDash.
        button:
          title: Elastisys
          url: https://elastisys.com
      support:
        header: Service
        body: If you need help with the cluster, please go here.
        button:
          title: Service Desk
          url: mailto:support@elastisys.com
