apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ck8sdash.fullname" . }}
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ck8sdash.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ck8sdash.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ck8sdash.serviceAccountName" . }}
      initContainers:
      - name: create-grafana-api-key
        image: elastisys/curl-jq
        command: ['sh', '/scripts/init.sh']
        env:
        - name: GRAFANA_USERNAME
          value: {{ .Values.grafana.username }}
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{include "ck8sdash.fullname" . }}-secrets
              key: grafana-password
        - name: GRAFANA_URL
          value: {{ .Values.grafana.url }}
        - name: GRAFANA_API_KEY_NAME
          value: {{ .Values.grafana.apiKeyName }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      containers:
      - name: ck8sdash-nginx
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        resources:
          {{- toYaml .Values.nginx.resources | nindent 12 }}
        # Note that these values are not reloaded if the secret is changed
        # The pod needs to be restarted to load new values
        env:
        - name: API_SERVER #ck8sdash-server port
          value: localhost:{{ .Values.server.port }}
        - name: PORT
          value: "{{ .Values.nginx.port }}"
        ports:
        - containerPort: {{ .Values.nginx.port }}
      - name: ck8sdash-server
        image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        resources:
          {{- toYaml .Values.server.resources | nindent 12 }}
        volumeMounts:
        - name: info-text
          mountPath: /info-text
        # Note that these values are not reloaded if the secret is changed
        # The pod needs to be restarted to load new values
        env:
        - name: PORT
          value: "{{ .Values.server.port }}"
        - name: INFO_PATH
          value: /info-text/info.json
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              name: ck8sdash-grafana-api-key
              key: grafana-api-key
        - name: GRAFANA_URL
          value: {{ .Values.grafana.url }}
        - name: HARBOR_URL
          value: {{ .Values.harbor.url }}
        - name: KIBANA_URL
          value: {{ .Values.kibana.url }}
        - name: ELASTIC_URL
          value: {{ .Values.elastic.url }}
        - name: OIDC_URL
          value: {{ .Values.oidc.url }}
        - name: HARBOR_USERNAME
          value: {{ .Values.harbor.username }}
        - name: HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{include "ck8sdash.fullname" . }}-secrets
              key: harbor-password
        - name: ELASTIC_USERNAME
          value: {{ .Values.elastic.username }}
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{include "ck8sdash.fullname" . }}-secrets
              key: elastic-password
        - name: OIDC_CLIENT_ID
          value: {{ .Values.oidc.clientId }}
        - name: OIDC_SECRET
          valueFrom:
            secretKeyRef:
              name: {{include "ck8sdash.fullname" . }}-secrets
              key: oidc-secret
        - name: ENABLE_OPA
          value: {{ quote .Values.opa.enabled }}
        - name: ENABLE_FALCO
          value: {{ quote .Values.falco.enabled }}
        - name: ELASTIC_KUBERNETES_INDEX_PREFIX
          value: {{ .Values.elastic.kubernetesIndexPrefix }}
        - name: ELASTIC_COMPONENTS_INDEX_PREFIX
          value: {{ .Values.elastic.componentsIndexDefault }}
        - name: GRAFANA_DATASOURCE
          value: {{ .Values.grafana.datasource }}
        ports:
        - containerPort: {{ .Values.server.port }}
      volumes:
      - name: scripts
        configMap:
          name: {{ include "ck8sdash.fullname" . }}-init-script
      - name: info-text
        configMap:
          name: {{ include "ck8sdash.fullname" . }}-info-text
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
