apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ck8sdash.serviceAccountName" . }}
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ck8sdash.fullname" . }}-secret-creator
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - "ck8sdash-grafana-api-key"
  - "ck8sdash-elastic-api-key"
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ck8sdash.fullname" . }}-secret-creator
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ck8sdash.fullname" . }}-secret-creator
subjects:
- kind: ServiceAccount
  name: {{ include "ck8sdash.serviceAccountName" . }}