---
- hosts: masters[0]
  become: yes
  become_user: root
  tasks:
    - name: Get join token
      command: kubeadm token create
      register: string_result

    - name: Store join token
      set_fact:
        join_token: "{{ string_result.stdout }}"

    - name: Get CA key hash
      shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
      register: string_result

    - name: Store CA key hash
      set_fact:
        ca_key_hash: "{{ string_result.stdout }}"

- hosts: workers
  become: yes
  become_user: root
  tasks:

    - name: Render kubeadm join config
      template:
        src: kubeadm-join.yaml.j2
        dest: /etc/kubeadm/kubeadm-join.yaml

    - name: Join the cluster
      command: "kubeadm join --config /etc/kubeadm/kubeadm-join.yaml"
      args:
        creates: /etc/kubernetes/kubelet.conf
