---
- hosts: nodes
  become: yes
  become_user: root
  tasks:

    - name: Create directories for kubeadm and kubernetes
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/kubeadm
        - /etc/kubernetes

    - name: Render cloud.conf
      when: cloud_config is defined
      template:
        src: cloud.conf.j2
        dest: "{{ cloud_config }}"

- hosts: masters
  become: yes
  become_user: root
  tasks:

    - name: Create conf directory for kubernetes
      file:
        path: /etc/kubernetes/conf
        state: directory

    - name: Create audit log directory
      file:
        path: /var/log/kube-audit
        state: directory

    - name: Add audit policy
      copy:
        src: files/audit-policy.yaml
        dest: /etc/kubernetes/conf/audit-policy.yaml
        owner: root
        group: root
        mode: '0644'
