---
- hosts: nodes
  become: yes
  become_user: root
  roles:
    - k8s_node

- hosts: internal_lb
  become: yes
  become_user: root
  gather_facts: false
  roles:
    - internal_lb

- hosts: masters
  become: yes
  become_user: root
  gather_facts: false
  tasks:

    - name: Create directories for kubernetes and audit logs
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/kubernetes/conf
        - /var/log/kube-audit

    - name: Add audit policy
      copy:
        src: files/audit-policy.yaml
        dest: /etc/kubernetes/conf/audit-policy.yaml
        owner: root
        group: root
        mode: '0644'
