- name: Create directories for kubeadm and kubernetes
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/kubeadm
    - /etc/kubernetes

- name: Render cloud.conf
  when: cloud_config is defined
  template:
    src: cloud.conf.j2
    dest: "{{ cloud_config }}"
