apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: elastic-system
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            # https://hub.docker.com/r/bobrik/curator/tags/
            image: bobrik/curator:5.7.6
            imagePullPolicy: IfNotPresent
            args: 
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: elastic-system
  labels:
    app: curator
data:
  action_file.yml: |-
    ---    
    actions:
      1:
        action: delete_indices
        description: "Clean up the oldest logstash-* indices that exceeds total disk space $AL_RETENTION_SIZE GB "
        options:
          continue_if_exception: False
          ignore_empty_list: True
          allow_ilm_indices: True
        filters:
        # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
        - filtertype: pattern
          kind: regex
          value: 'logstash-*'
        - filtertype: space
          disk_space: $AL_RETENTION_SIZE
          use_age: True
          source: creation_date
        - filtertype: kibana
          exclude: True
      2:
        action: delete_indices
        description: "Clean up the logstash-* indices that are older then $AL_RETENTION_AGE days"
        options:
          continue_if_exception: False
          ignore_empty_list: True
          allow_ilm_indices: True
        filters:
        # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
        - filtertype: pattern
          kind: regex
          value: 'logstash-*'
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: $AL_RETENTION_AGE
        - filtertype: kibana
          exclude: True  
      3:
        action: delete_indices
        description: "Clean up the oldest kubecomponents-* indices that exceeds total disk space $APIL_RETENTION_SIZE GB"
        options:
          continue_if_exception: False
          ignore_empty_list: True
          allow_ilm_indices: True
        filters:
        # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
        - filtertype: pattern
          kind: regex
          value: 'kubecomponents-*'
        - filtertype: space
          disk_space: $APIL_RETENTION_SIZE
          use_age: True
          source: creation_date
        - filtertype: kibana
          exclude: True
      4:
        action: delete_indices
        description: "Clean up the kubecomponents-* indices that are older then $APIL_RETENTION_AGE days"
        options:
          continue_if_exception: False
          ignore_empty_list: True
          allow_ilm_indices: True
        filters:
        # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
        - filtertype: pattern
          kind: regex
          value: 'kubecomponents-*'
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: $APIL_RETENTION_AGE
        - filtertype: kibana
          exclude: True

  config.yml: |-
    ---
    client:
      hosts:
        - elasticsearch-es-http
      port: 9200
      use_ssl: True 
      ssl_no_validate: True
      http_auth: elastic:$ES_PW
      timeout: 30
      master_only: False
    logging:
      loglevel: DEBUG
      logformat: default
      # This is the default blacklist
      blacklist: ['elasticsearch', 'urllib3']