apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: elastic-system
spec:
  # Run every 5 minutes
  schedule: "5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            # https://hub.docker.com/r/bobrik/curator/tags/
            image: bobrik/curator:5.7.6
            imagePullPolicy: IfNotPresent
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: elastic-system
  labels:
    app: curator
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    actions:
      1:
        action: delete_indices
        description: "Clean up elasticsearch by deleting old indices."
        options:
          continue_if_exception: False
          ignore_empty_list: True
          allow_ilm_indices: True
        filters:
        # https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filters.html
        - filtertype: space
          disk_space: 1
          use_age: True
          source: creation_date
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 30
        - filtertype: kibana
          exclude: True
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - elasticsearch-logging
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      # This is the default blacklist
      blacklist: ['elasticsearch', 'urllib3']