apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 7.3.1
  nodes:
  - nodeCount: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      plugin.mandatory: repository-s3
      s3.client.default.endpoint: ${S3_REGION_ENDPOINT}
      s3.client.default.protocol: https
    podTemplate:
      spec:
        initContainers:
        - name: install-s3-plugin
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        containers:
        - name: elasticsearch 
          resources:
            requests:
              memory: 2Gi
              cpu: 0.3
            limits:
              memory: 3Gi
              cpu: 1
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: common.k8s.elastic.co/type
                    operator: In
                    values:
                    - elasticsearch
                topologyKey: "kubernetes.io/hostname"

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: ${STORAGE_CLASS}
  secureSettings:
    secretName: s3-credentials