ingress:
  enabled: true
  #annotations:
  #  certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - dex.compliantk8s.com
  tls:
    - secretName: dex-tls
      hosts:
        - dex.compliantk8s.com

certs:
  web:
    create: false
  grpc:
    create: true

config:
  issuer: https://dex.compliantk8s.com
  web:
    http: 0.0.0.0:8080
  connectors:
  - type: oidc
    id: google
    name: Google
    config:
      # Canonical URL of the provider, also used for configuration discovery.
      # This value MUST match the value returned in the provider config discovery.
      #
      # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
      issuer: https://accounts.google.com

      # Connector config values starting with a "$" will read from the environment. 
      # Change this to a new google cloud project.
      clientID: 556379655797-vdbk7mmj1ggro13v4q4eivsd65mvs3d2.apps.googleusercontent.com
      clientSecret: 19g7vy1e9zEAlO6hf7jhYEkJ 

      # Dex's issuer URL + "/callback"
      redirectURI: https://dex.compliantk8s.com/callback
  
  staticClients:
    - id: kubernetes
      redirectURIs:
        - 'http://localhost:8000'
        - 'https://dashboard.compliantk8s.com/oauth2/callback'
        - 'https://dashboard-customer.compliantk8s.com/oauth2/callback'
      name: 'Kubernetes dashboard'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  enablePasswordDB: true
  staticPasswords:
    - email: "admin@example.com"
      # bcrypt hash of the string "password"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
