ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  path: /
  tls:
    - secretName: dex-tls

certs:
  web:
    create: false
  grpc:
    create: true

config:
  web:
    http: 0.0.0.0:8080
  connectors:
  - type: oidc
    id: google
    name: Google
    config:
      # Canonical URL of the provider, also used for configuration discovery.
      # This value MUST match the value returned in the provider config discovery.
      #
      # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
      issuer: https://accounts.google.com
  staticClients:
    - id: kubernetes
      name: 'Kubernetes dashboard'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
