expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-certs
  ingress:
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    chartmuseum:
      existingClaim: "harbor-chartmuseum-claim"
      accessModes: ReadWriteOnce
      storageClass: "nfs-client"
      subPath: "chartmuseum"
      size: 5Gi
    registry:
      existingClaim: "harbor-registry-claim"
      accessModes: ReadWriteOnce
      storageClass: "nfs-client"
      subPath: "registry"
      size: 5Gi
    jobservice:
      existingClaim: "harbor-jobservice-claim"
      accessModes: ReadWriteOnce
      storageClass: "nfs-client"
      subPath: "jobservice"
      size: 1Gi
    database:
      existingClaim: "harbor-database-claim"
      accessModes: ReadWriteOnce
      storageClass: "nfs-client"
      subPath: "database"
      size: 1Gi
    redis:
      existingClaim: "harbor-redis-claim"
      accessModes: ReadWriteOnce
      storageClass: "nfs-client"
      subPath: "redis"
      size: 1Gi
    #externalURL: https://core.harbor.harbor
  imageChartStorage:
    type: s3
    s3:
      region: de-fra-1
      regionendpoint: "https://sos-de-fra-1.exo.io"
      bucket: harbor-bucket
