expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: core.harbor.test.compliantk8s.com
      notary: notary.harbor.test.compliantk8s.com
    # The chart interferes with this annotation so we have to add it later
    # annotations:
    #   certmanager.k8s.io/cluster-issuer: letsencrypt-staging
ingress:
  tls:
    - secretName: harbor-certs
      hosts:
        - core.harbor.test.compliantk8s.com
        - notary.harbor.test.compliantk8s.com

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    chartmuseum:
      existingClaim: "example-pvc"
      accessModes: ReadWriteOnce
      storageClass: "local-storage"
      subPath: "chartmuseum"
      size: 5Gi
    registry:
      existingClaim: "example-pvc"
      accessModes: ReadWriteOnce
      storageClass: "local-storage"
      subPath: "registry"
      size: 5Gi
    jobservice:
      existingClaim: "example-pvc"
      accessModes: ReadWriteOnce
      storageClass: "local-storage"
      subPath: "jobservice"
      size: 1Gi
    database:
      existingClaim: "example-pvc"
      accessModes: ReadWriteOnce
      storageClass: "local-storage"
      subPath: "database"
      size: 1Gi
    redis: 
      existingClaim: "example-pvc"
      accessModes: ReadWriteOnce
      storageClass: "local-storage"
      subPath: "redis"
      size: 1Gi
    #externalURL: https://core.harbor.harbor
  imageChartStorage:
    type: s3
    s3:
      region: de-fra-1
      regionendpoint: "https://sos-de-fra-1.exo.io"
      bucket: harbor-bucket

externalURL: https://core.harbor.test.compliantk8s.com
