expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-certs
  ingress:
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    chartmuseum:
      size: 5Gi
    registry:
      size: 5Gi
    jobservice:
      size: 1Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
  imageChartStorage:
    type: s3
    s3:
      region: de-fra-1
      regionendpoint: "https://sos-de-fra-1.exo.io"
      bucket: harbor-bucket
