# Can be deployed in kubernetes to debug networking issues.
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ubuntu-debug-deployment
#   labels:
#     app: ubuntu
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ubuntu
#   template:
#     metadata:
#       labels:
#         app: ubuntu
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: In
#                 values:
#                 - 89.145.163.4
#       volumes:
#           - name: task-pv-example
#             persistentVolumeClaim:
#               claimName: example-pvc
#       containers:
#         - image: lindqvist/ubuntu-debug
#           command:
#             - sleep
#           args: ["99999"]
#           name: ubuntu
#           ports:
#             - containerPort: 80
#           volumeMounts:
#           - mountPath: "/home2"
#             name: task-pv-example
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-debug-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - image: lindqvist/ubuntu-debug
          command:
            - sleep
          args: ["99999"]
          name: ubuntu
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-pvc
              mountPath: "/mnt2"
      # tolerations:
      nodeSelector: 
        env: worker
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: test-claim
          
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
      #   effect: "NoSchedule"
      # - key: node-role.kubernetes.io/controlplane
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"
      # - key: node-role.kubernetes.io/etcd
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoExecute"
