apiVersion: v1
kind: Namespace
metadata:
  name: restricted-namespace
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "env=worker"
    scheduler.alpha.kubernetes.io/tolerationsWhitelist: '[
    {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/unreachable"},
    {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/not-ready"}]'

# Following tolerations have to be whitelisted in order to run on master node
# {"operator": "Equal", "key": "node-role.kubernetes.io/controlplane", "effect": "NoSchedule", "value":"true"}
# {"operator": "Equal", "key": "node-role.kubernetes.io/etcd", "effect": "NoExecute", "value": "true"}
# Add to whitelist with correct operatior, key and value, and effect to whitelist taint
# {"operator": "Equal", "key": "key", "effect": "NoSchedule", "value":"value"}
