name: CI

on: [push]

jobs:
  infra:
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - run: ./pipeline/infra.sh
      shell: bash
      env:
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
        SSH_KEY_SC: ${{ secrets.SSH_KEY_SC }}
        SSH_KEY_WC: ${{ secrets.SSH_KEY_WC }}
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}
    - name: Upload infra.json
      uses: actions/upload-artifact@v1
      with:
        name: infra.json
        path: infra.json
    - name: upload terraform output
      uses: actions/upload-artifact@v1
      with:
        name: tfoutput        
        path: tfoutput

  rke-sc:
    needs: infra
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - run: ./pipeline/rke-sc.sh
      shell: bash
      env:
        SSH_KEY_SC: ${{ secrets.SSH_KEY_SC }}
        SSH_KEY_WC: ${{ secrets.SSH_KEY_WC }}
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}
    - name: Upload kube_config
      uses: actions/upload-artifact@v1
      with:
        name: kube_config_eck-sc.yaml
        path: kube_config_eck-sc.yaml
    - name: Upload rke output
      uses: actions/upload-artifact@v1
      with:
        name: rke-sc-output
        path: rke-sc-output

  rke-wc:
    needs: infra
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - run: ./pipeline/rke-wc.sh
      shell: bash
      env:
        SSH_KEY_SC: ${{ secrets.SSH_KEY_SC }}
        SSH_KEY_WC: ${{ secrets.SSH_KEY_WC }}
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}
    - name: Upload kube_config
      uses: actions/upload-artifact@v1
      with:
        name: kube_config_eck-wc.yaml
        path: kube_config_eck-wc.yaml
    - name: Upload rke output
      uses: actions/upload-artifact@v1
      with:
        name: rke-wc-output
        path: rke-wc-output

  deploy-sc:
    needs: [rke-sc,rke-wc]
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - name: Download kube_config
      uses: actions/download-artifact@v1
      with:
        name: kube_config_eck-sc.yaml
        path: .
    - run: ./pipeline/deploy-sc.sh
      shell: bash
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}

  deploy-wc:
    needs: [rke-sc,rke-wc]
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - name: Download kube_config
      uses: actions/download-artifact@v1
      with:
        name: kube_config_eck-wc.yaml
        path: .
    - run: ./pipeline/deploy-wc.sh
      shell: bash
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}
  
  test-sc:
    needs: [deploy-wc, deploy-sc]
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - name: Download kube_config
      uses: actions/download-artifact@v1
      with:
        name: kube_config_eck-sc.yaml
        path: .
    - run: ./pipeline/test-sc.sh
      shell: bash
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}

  test-wc:
    needs: [deploy-wc, deploy-sc]
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - name: Download infra.json
      uses: actions/download-artifact@v1
      with:
        name: infra.json
        path: .
    - name: Download kube_config
      uses: actions/download-artifact@v1
      with:
        name: kube_config_eck-wc.yaml
        path: .
    - run: ./pipeline/test-wc.sh
      shell: bash
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}

  clean-up:
    needs: [deploy-sc,deploy-wc]
    if: always()
    runs-on: ubuntu-latest
    container: 
      image: elastisys/ck8s-bitbucket-pipeline:1.0.6
    steps:
    - uses: actions/checkout@v1
    - run: ./pipeline/cleanup.sh
      shell: bash
      env: 
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
        SSH_KEY_SC: ${{ secrets.SSH_KEY_SC }}
        SSH_KEY_WC: ${{ secrets.SSH_KEY_WC }}
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_SECRET_KEY: ${{ secrets.EXOSCALE_SECRET_KEY }}
        VAULT_APPROLE_RID: ${{ secrets.VAULT_APPROLE_RID }}
        VAULT_APPROLE_SID: ${{ secrets.VAULT_APPROLE_SID }}
