name: Release

on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            See [CHANGELOG.md](https://github.com/elastisys/ck8s/blob/${{ github.ref }}/CHANGELOG.md) for details.
                      
  build-image:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: "${{ secrets.DOCKERHUB_USER }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: elastisys/ck8s-ops
        image_tag: ${{ github.ref }}
        context: pipeline
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: "${{ secrets.DOCKERHUB_USER }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: elastisys/ck8s-ops
        image_tag: latest
        context: pipeline
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: "${{ secrets.DOCKERHUB_USER }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: elastisys/ck8s-ops
        image_tag: ${{ github.ref }}-dev
        context: pipeline
        dockerfile: Dockerfile.dev
