name: Safespring-pipeline

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: "${{ secrets.DOCKERHUB_USER }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: elastisys/ck8s-ops
        image_tag: ${{ github.sha }}
        context: pipeline

  init:
    needs: build-image
    runs-on: ubuntu-latest
    container:
      image: elastisys/ck8s-ops:${{ github.sha }}
    steps:
    - uses: actions/checkout@v1
    - run: ./pipeline/init.bash
      shell: bash
      env:
        CK8S_CONFIG_PATH: ./ck8s_pipeline_config
        CK8S_CLOUD_PROVIDER: safespring
        PGP_KEY: ${{ secrets.PGP_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
        # Prefixed with CI to prevent confusing people they are used from env
        # and not from secrets.env.
        CI_OS_USERNAME: ${{ secrets.SAFESPRING_OS_USERNAME }}
        CI_OS_PASSWORD: ${{ secrets.SAFESPRING_OS_PASSWORD }}
        CI_S3_ACCESS_KEY: ${{ secrets.SAFESPRING_S3_ACCESS_KEY }}
        CI_S3_SECRET_KEY: ${{ secrets.SAFESPRING_S3_SECRET_KEY }}
        CI_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        CI_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload config
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: ck8s-config
        path: ./ck8s_pipeline_config

  apply:
    needs: init
    runs-on: ubuntu-latest
    container:
      image: elastisys/ck8s-ops:${{ github.sha }}
    steps:
    - uses: actions/checkout@v1
    - name: Download config
      uses: actions/download-artifact@v1
      with:
        name: ck8s-config
        path: ./ck8s_pipeline_config
    - run: ./pipeline/apply.bash
      shell: bash
      env:
        CK8S_CONFIG_PATH: ./ck8s_pipeline_config
        PGP_KEY: ${{ secrets.PGP_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
    - name: Upload config
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: ck8s-config
        path: ./ck8s_pipeline_config

  cleanup:
    needs: apply
    if: always()
    runs-on: ubuntu-latest
    container:
      image: elastisys/ck8s-ops:${{ github.sha }}
    steps:
    - uses: actions/checkout@v1
    - name: Download config
      uses: actions/download-artifact@v1
      with:
        name: ck8s-config
        path: ./ck8s_pipeline_config
    - run: ./pipeline/cleanup.bash
      shell: bash
      env:
        CK8S_CONFIG_PATH: ./ck8s_pipeline_config
        PGP_KEY: ${{ secrets.PGP_KEY }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
