apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default:restricted-psp
  namespace: default
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:restricted-psp
  namespace: default
roleRef:
  kind: Role
  name: default:restricted-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
