apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system:default-psp
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use