apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system:default-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-system:default-psp
subjects:
- kind: ServiceAccount
  name: rke-job-deployer
  namespace: kube-system
